### ISSUE TITLE
Utilizar palavras em inglês

### ISSUE THREAD

**Issue by edmargomes** [flavinha-ribeiro/-formulario-teste#1]
Nos atributos name e id devemos sempre usar as palavras em inglês , elas também não podem conter espaço ou caracteres especiais.

Checar todo o formulário para trocar em todos os locais

https://github.com/flavinha-ribeiro/-formulario-teste/blob/a622362cd275e6fa7fb571d6f4c36e8edb372c5b/index.php#L13

OBS: @flavinha-ribeiro você não trocou o usuario do git que está na máquina e esta enviando o codigo como se fosse o Daniel

**Comment by flavinha-ribeiro** [comment]
Já troquei o usuário e mudei para o inglês espero que tenha dado certo.
