### ISSUE TITLE
Tag input não fechada no html

### ISSUE THREAD

**Issue by edmargomes** [flavinha-ribeiro/-formulario-teste#2]
A tag input não foi fechada no html igual as outras, se vc abrir esse arquivo index.php no github irá ver algumas marcações de vermelho pelo fato de fechar a tag

https://github.com/flavinha-ribeiro/-formulario-teste/blob/a622362cd275e6fa7fb571d6f4c36e8edb372c5b/index.php#L35

**Comment by flavinha-ribeiro** [comment]
Corrigido
