### ISSUE TITLE
Por que tem esse campo?

### ISSUE THREAD

**Issue by edmargomes** [flavinha-ribeiro/-formulario-teste#4]
Qual a necessidade desse campo Buscar?
https://github.com/flavinha-ribeiro/-formulario-teste/blob/a622362cd275e6fa7fb571d6f4c36e8edb372c5b/index.php#L49

**Comment by flavinha-ribeiro** [comment]
Ja retirei,kk

**Comment by flavinha-ribeiro** [comment]
Já Excluir
